[build]
  publish = "build/"
  command = "./scripts/netlify.sh"

[context.production.environment]
  SECRETHUB_ENV = "prod"

[context.deploy-preview.environment]
  SECRETHUB_ENV = "dev"

[context.dev.environment]
  SECRETHUB_ENV = "dev"
