[build]
  publish = "build/"
  command = "./scripts/netlify.sh"
  functions = "./functions/"

[build.environment]
  # cache Cypress binaries together with node_modules
  CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
  CYPRESS_SPEC = "cypress/integration/**/*.js"

[context.production.environment]
  SECRETHUB_ENV = "prod"

[context.deploy-preview.environment]
  SECRETHUB_ENV = "dev"

[context.dev.environment]
  SECRETHUB_ENV = "dev"

[[plugins]]
  package = "netlify-plugin-cypress"
  spec = "$CYPRESS_SPEC"