name: Debug Action

on:
  repository_dispatch:
    types: [deploy_succeeded]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - if: ${{ github.event.client_payload.deploy.context == "production" }}
        run: echo "run smoke tests"

      - if: ${{ github.event.client_payload.deploy.context != "production" }}
        run: echo "run all tests"
