name: E2E tests

on:
  repository_dispatch:
    types: [deploy_succeeded]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: cypress-io/github-action@master
        # if: ${{ github.event.client_payload.deploy.context != "production" }}
        with:
          browser: chrome
          headless: true
          config: baseUrl=${{ github.event.client_payload.deploy.deploy_url }}
